name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy
      run: |
        echo "Deploying the project..."
        # Add your deployment steps here
        # Example: ssh to your server and deploy
        # ssh user@server 'cd /path/to/app && git pull && npm install && npm run build && pm2 restart app'
